enableGlobalCache: true

nodeLinker: node-modules

packageExtensions:
  react-scripts@*:
    dependencies:
      "@pmmmwh/react-refresh-webpack-plugin": "*"
    peerDependencies:
      react: "*"

yarnPath: .yarn/releases/yarn-berry.cjs
